version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: eleven_fantasy_db
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: fantasy
      POSTGRES_PASSWORD: fantasy_password
      POSTGRES_DB: eleven_fantasy
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
